language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - mkdir temp
  - cd temp
  - wget https://raw.githubusercontent.com/afiskon/install-couchdb/master/install-couchdb.sh
  - sudo sh install-couchdb.sh
  - sleep 10
  - curl -X PUT localhost:5984/doctrine_test_database
  - composer install

script:
  - php vendor/bin/phpunit
